/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Component;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jhonny
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
   public static estados matriz[][];
    public index() {
        initComponents();
        this.setLocationRelativeTo(this);
        matriz=new estados[15][12];
        analizador.listacadena=new LinkedList();
        tokens.list=new LinkedList();
     analizador.tmp=new LinkedList();

analizador.llenarmatriz();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        Token = new javax.swing.JButton();
        letratoken = new javax.swing.JLabel();
        tipotoken = new javax.swing.JLabel();
        LETTER = new javax.swing.JLabel();
        TOKEN = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 15, 107));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(194, 110, 22));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setText("ANALIZADOR LEXICO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 450, 60));

        jLabel2.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        jLabel2.setText("Version 1.0");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, -1, -1));

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Buscar archivo");
        search.setBorder(null);
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 130, 50));

        texto.setBackground(new java.awt.Color(153, 153, 255));
        texto.setColumns(20);
        texto.setForeground(new java.awt.Color(102, 102, 102));
        texto.setRows(4);
        texto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jScrollPane1.setViewportView(texto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 270));

        Token.setText("Obtener token");
        Token.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TokenActionPerformed(evt);
            }
        });
        jPanel1.add(Token, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 140, 40));

        letratoken.setBackground(new java.awt.Color(153, 0, 0));
        letratoken.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        letratoken.setForeground(new java.awt.Color(255, 255, 255));
        letratoken.setText("LETRA");
        jPanel1.add(letratoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 100, -1));

        tipotoken.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        tipotoken.setForeground(new java.awt.Color(255, 255, 255));
        tipotoken.setText("TOKEN");
        jPanel1.add(tipotoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        LETTER.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        LETTER.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(LETTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 160, 20));

        TOKEN.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        TOKEN.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(TOKEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 150, 30));

        jButton1.setText("ANALIZADOR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 130, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
leer();
texto.setText(analizador.Texto);
String array[]=analizador.Texto.split("l1");
for(int i=0; i<array.length;i++){

}
texto.disable();
 analizador tmp=new analizador();
   
for(int i=0; i<analizador.lista.size();i++){
tmp.analizar(analizador.lista.get(i));
}
tokens.toknes();
leeR();
    }//GEN-LAST:event_searchActionPerformed
int count=0;
public void leeR(){


}
    private void TokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TokenActionPerformed
    
 //System.out.println(analizador.tmp.get(count).getLetra()+" "+analizador.tmp.get(count).getTipo());
  // System.out.println(tokens.list.get(count).getLetra());
  try{
 LETTER.setText(tokens.list.get(count).getLetra());
 TOKEN.setText(tokens.list.get(count).getToken());
    
   count++;
  }catch(IndexOutOfBoundsException e){
  JOptionPane.showMessageDialog(this, "No hay mas tokens a procesar----->");
  }
  
    }//GEN-LAST:event_TokenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        analizadorsintatic g=new analizadorsintatic();
        g.show();
    }//GEN-LAST:event_jButton1ActionPerformed
public void leer(){
//Creamos el objeto JFileChooser
JFileChooser fc=new JFileChooser();
//Indicamos lo que podemos seleccionar
fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
//Creamos el filtro
FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", ".txt");
//Le indicamos el filtro
fc.setFileFilter(filtro);
Component contentPane = null;
//Abrimos la ventana, guardamos la opcion seleccionada por el usuario
int seleccion=fc.showOpenDialog(contentPane);
//Si el usuario, pincha en aceptar

analizador.leer(seleccion, fc);
 

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LETTER;
    private javax.swing.JLabel TOKEN;
    private javax.swing.JButton Token;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel letratoken;
    private javax.swing.JButton search;
    private static javax.swing.JTextArea texto;
    private javax.swing.JLabel tipotoken;
    // End of variables declaration//GEN-END:variables
}
